name: ejazah
description: New Flutter Project Developed By Visooft Team
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  fluttertoast: ^8.2.1
  modal_bottom_sheet: ^2.1.2
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  get: ^4.6.5
  custom_check_box: ^0.0.4
  # otp_text_field: ^1.1.3
  flutter_countdown_timer: ^4.1.0
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  intl: 
  badges: ^3.0.2
  chewie: ^1.4.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.3
  modal_progress_hud_nsn: ^0.3.0
  grouped_list: ^5.1.2
  flutter_rating_bar: ^4.0.1
  flutter_fortune_wheel: ^1.3.0
  sizer: ^2.0.15
  flutter_carousel_slider: ^1.1.0
  syncfusion_flutter_sliders: ^20.4.53
  syncfusion_flutter_datepicker: ^20.4.54
  expandable_text: ^2.3.0
  http: ^0.13.5
  form_field_validator: ^1.1.0
  # multiselect: ^0.1.0
  # edit by oliver

  animate_do: ^3.0.2
  iconly: ^1.0.1
  image_picker: ^0.8.6+1
  cached_network_image: ^3.2.3
  http_parser: ^4.0.2
  dio: ^5.1.1
  location: ^4.4.0
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  geocoding: ^2.0.5
  shared_preferences: ^2.1.0
  slide_countdown: ^0.5.0
  firebase_messaging: ^14.2.1
  awesome_notifications: any
#  awesome_notifications_fcm: ^0.7.4+1
  flutter_svg:
  flutter_html:
  firebase_storage: ^11.1.1
  file_picker:
  moyasar: ^2.0.0
  flutter_credit_card: ^3.0.7
  pin_code_fields: ^8.0.1
  rxdart: ^0.27.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/NotoSansArabic-Regular.ttf
# NotoSansArabic